config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs
  resources :articles
  resources :users
  resources :sessions

  root 'users#index'

  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :articles

  def is_owner?(user)
    return false unless user
    user_id === user.id
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i(show edit update destroy)
  before_action :authorize, only: %i(new edit create update destroy)
  before_action :validate_user, only: %i(edit update destroy)

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new(user_id: current_user.id)
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params_for_create)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params_for_update)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def validate_user
      unless @blog.is_owner? current_user
        redirect_to blogs_url, notice: "The blog is not yours."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params_for_create
      params[:blog][:user_id] = current_user.id
      params.require(:blog).permit(:name, :user_id)
    end

    def blog_params_for_update
      params.require(:blog).permit(:name)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:name) %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1><%=t :edit_object, obj: t(:blog) %></h1>

<%= render 'form' %>

<%= link_to t(:back), @blog  %>

app/views/blogs/new.html.erb
<h1><%=t :create_object, obj: t(:blog) %></h1>

<%= render 'form' %>

<%= link_to t(:back), @blog.user %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @blog.name %></h3>
<% if @blog.articles.present? %>
  <% @blog.articles.each do |article| %>
    <div class="row">
      <div class="col-sm-12 body">
        <small><%= format_date article.created_at %></small>
        <h4 class="section"><%= link_to article.title, article %></h4>
        <div class="row">
          <div class="col-sm-12">
            <%= format_text article.body %>
          </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-sm-12">
      <%=t :no_object, obj: t(:article) %>
    </div>
  </div>
  <br>
<% end %>
<% if @blog.is_owner? current_user %>
  <%= link_to t(:write_object, obj: t(:article)), new_article_path(blog_id: @blog.id) %> |
  <%= link_to t(:edit_object, obj: t(:blog)), edit_blog_path(@blog)  %> |
<% end %>
<%= link_to t(:back), @blog.user %>