config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs
  resources :articles
  resources :users
  resources :sessions

  root 'users#index'

  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true

  has_many :blogs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, except: %i(index show new create)
  before_action :set_user, only: %i(show edit update destroy)
  before_action :validate_user!, only: %i(edit update destroy)

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.valid? && @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.valid? && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_user!
      unless current_user && @user.id === current_user.id
        redirect_to users_url, notice: "You can operate only your account."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:name) %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label t(:password) %><br>
    <%= f.text_field :password, type: "password", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label t(:password_confirmation) %><br>
    <%= f.text_field :password_confirmation, type: "password", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%=t :edit_account %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= @notice %></p>

<h1><%=t :user_list %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%=t :name %></th>
      <th><%=t :registration_date %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= format_ja_date user.created_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><% if current_user && current_user.id == user.id %><%= link_to 'Edit', edit_user_path(user) %><% end %></td>
        <td><% if current_user && current_user.id == user.id %><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1><%=t :sign_up %></h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%=t :blog_list_of, user: @user.name %></h3>

<table class="table">
  <thead>
    <tr>
      <th><%=t :blog %></th>
      <th><%=t :updated_date %></th>
    </tr>
  </thead>
  <tbody>
    <% if @user.blogs.present? %>
      <% @user.blogs.each do |blog| %>
        <tr>
          <td><%= link_to blog.name, blog %></td>
          <td><%= format_ja_datetime blog.updated_at %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="2"></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user && current_user.try(:id) == @user.id %>
  <%= link_to t(:create_object, obj: t(:blog)), new_blog_path %> |
<% end %>
<%= link_to t(:back), users_path %>