config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs
  resources :articles
  resources :users
  resources :sessions

  root 'users#index'

  match 'signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'bootstrap.min' %>
  <%= stylesheet_link_tag 'bootstrap-theme.min' %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Blog</a>
      </div>
      <div class="collapse navbar-collapse bs-navbar-collapse">
        <div class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%=t :menu %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to t(:edit_account), edit_user_path(current_user) %></li>
                <li><%= link_to t(:logout), signout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'login', new_session_path %></li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container main-container">
    <div class="row">
      <div class="col-sm-offset-1 col-sm-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>